### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by johngrabner** [jbaiter/archiscribe-corpus#2]
I was hoping you could describe the mapping of files in the folders under /transcription to the table Statistics: Works?

Your transcriptions are single line, but the links in the column Archive.org and IIF are full pages.

My interest is in full-page OCR, so I would like to scan the full page corresponding to your cropped line and use the provided transcribe line as an indication of the OCR quality.

Regards,
John Grabner

**Comment by jbaiter** [comment]
> I was hoping you could describe the mapping of files in the folders under /transcription to the table Statistics: Works?

The table is generated from the JSON files in each year's subdirectory, one for each volume from that year, e.g. for 1897: https://github.com/jbaiter/archiscribe-corpus/blob/master/transcriptions/1897/allgemeinekultu12rhyngoog.json

> Your transcriptions are single line, but the links in the column Archive.org and IIF are full pages.

The JSON file has IIIF Image API URLs that target the transcribed line, e.g. (in the above file):

![](https://iiif.archivelab.org/iiif/allgemeinekultu12rhyngoog$41/405,1432,2364,83/full/0/default.png)
https://github.com/jbaiter/archiscribe-corpus/blob/master/transcriptions/1897/allgemeinekultu12rhyngoog.json#L10

**Comment by johngrabner** [comment]
thank you
